### ISSUE TITLE
error parsing the attached valid mof

### ISSUE THREAD

**Issue by pursca** [KingslandConsulting/Kingsland.MofParser#61]
System.InvalidOperationException
  HResult=0x80131509
  Message=Operation is not valid due to the current state of the object.
  Source=Kingsland.MofParser
  StackTrace:
   at Kingsland.MofParser.Objects.Instance.FromAstNode(InstanceValueDeclarationAst node) in C:\src\github\mikeclayton\MofParser\src\Kingsland.MofParser\Objects\Instance.cs:line 69
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Kingsland.MofParser.PowerShellDscHelper.ParseMofFileInstances(String filename) in C:\src\github\mikeclayton\MofParser\src\Kingsland.MofParser\PowerShellDscHelper.cs:line 32
   at PowerSTIGStateKeeper.MofHelper.Test() in C:\Users\jlee\Source\Repos\PowerSTIGStateKeeper\PowerSTIGStateKeeper\MofHelper.cs:line 16
   at PowerSTIGStateKeeper.Program.Main(String[] args) in C:\Users\jlee\Source\Repos\PowerSTIGStateKeeper\PowerSTIGStateKeeper\Program.cs:line 22

[localhost.zip](https://github.com/KingslandConsulting/Kingsland.MofParser/files/4886350/localhost.zip)

**Comment by mikeclayton** [comment]
Minimal repro:

```
instance of NTFSAccessControlList as $NTFSAccessControlList1ref
{
  AccessControlEntry = {
    $NTFSAccessControlEntry1ref
  };
};
```

The ```Instance.FromAstNode" method doesn't currently like anything other than literal values or literal arrays, and the alias reference ```$NTFSAccessControlEntry1ref``` is a complex type.

I've got a fix which I'll push and merge shortly...

As an aside, I'm not really a fan of the Instance class - it feels like there needs to be a full and proper domain model instead that the AST nodes can be converted to, but that's more work than I can really commit to at the moment. Maybe one day...

**Comment by mikeclayton** [comment]
Should be resolved from PR above. Yell if it you still have problems...
